### ISSUE TITLE
LED 0, 1541 activity lit constantly even with 2dosa_c .bin flashed

### ISSUE THREAD

**Issue by BennehBoy** [vossstef/VIC20Nano#6]
I've flashed vic20nano_tn20k.fs & 2_dos_c.bin using openFPGAloader under linux but the nano starts up with a black screen & the 1541 LED constantly lit.

I do not have an m0s dock connected yet (it's on order), is this required for the system to boot?

With C64nano & the same dos image flashed the tang boots to the C64 basic prompt and LED 0 is not lit - so I had assumed the vic would also make it to the basic prompt.

**Comment by vossstef** [comment]
If i recall right i implemented that core remains in reset in case no M0S dock attached.

**Comment by BennehBoy** [comment]
> If i recall right i implemented that core remains in reset in case no M0S dock attached.



> If i recall right i implemented that core remains in reset in case no M0S dock attached.

Thanks, that makes perfect sense, awaiting the slow boast from China now :D

**Comment by vossstef** [comment]
@BennehBoy  is your issue sollen?
